# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fmain.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_fmain(object):
    def setupUi(self, fmain):
        if not fmain.objectName():
            fmain.setObjectName(u"fmain")
        fmain.resize(846, 617)
        self.btReset = QPushButton(fmain)
        self.btReset.setObjectName(u"btReset")
        self.btReset.setGeometry(QRect(760, 10, 44, 40))
        self.btReset.setStyleSheet(u"border-radius:25")
        icon = QIcon()
        icon.addFile(u"Img/restart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btReset.setIcon(icon)
        self.btReset.setIconSize(QSize(40, 40))
        self.bt_1 = QPushButton(fmain)
        self.bt_1.setObjectName(u"bt_1")
        self.bt_1.setGeometry(QRect(20, 60, 121, 171))
        icon1 = QIcon()
        icon1.addFile(u"Img/baralho.png", QSize(), QIcon.Normal, QIcon.Off)
        self.bt_1.setIcon(icon1)
        self.bt_1.setIconSize(QSize(151, 171))
        self.bt_2 = QPushButton(fmain)
        self.bt_2.setObjectName(u"bt_2")
        self.bt_2.setGeometry(QRect(160, 60, 121, 171))
        self.bt_2.setIcon(icon1)
        self.bt_2.setIconSize(QSize(151, 171))
        self.bt_3 = QPushButton(fmain)
        self.bt_3.setObjectName(u"bt_3")
        self.bt_3.setGeometry(QRect(300, 60, 121, 171))
        self.bt_3.setIcon(icon1)
        self.bt_3.setIconSize(QSize(151, 171))
        self.bt_4 = QPushButton(fmain)
        self.bt_4.setObjectName(u"bt_4")
        self.bt_4.setGeometry(QRect(440, 60, 121, 171))
        self.bt_4.setIcon(icon1)
        self.bt_4.setIconSize(QSize(151, 171))
        self.bt_5 = QPushButton(fmain)
        self.bt_5.setObjectName(u"bt_5")
        self.bt_5.setGeometry(QRect(580, 60, 121, 171))
        self.bt_5.setIcon(icon1)
        self.bt_5.setIconSize(QSize(151, 171))
        self.bt_6 = QPushButton(fmain)
        self.bt_6.setObjectName(u"bt_6")
        self.bt_6.setGeometry(QRect(720, 60, 121, 171))
        self.bt_6.setIcon(icon1)
        self.bt_6.setIconSize(QSize(151, 171))
        self.bt_7 = QPushButton(fmain)
        self.bt_7.setObjectName(u"bt_7")
        self.bt_7.setGeometry(QRect(20, 240, 121, 171))
        self.bt_7.setIcon(icon1)
        self.bt_7.setIconSize(QSize(151, 171))
        self.bt_8 = QPushButton(fmain)
        self.bt_8.setObjectName(u"bt_8")
        self.bt_8.setGeometry(QRect(160, 240, 121, 171))
        self.bt_8.setIcon(icon1)
        self.bt_8.setIconSize(QSize(151, 171))
        self.bt_9 = QPushButton(fmain)
        self.bt_9.setObjectName(u"bt_9")
        self.bt_9.setGeometry(QRect(300, 240, 121, 171))
        self.bt_9.setIcon(icon1)
        self.bt_9.setIconSize(QSize(151, 171))
        self.bt_10 = QPushButton(fmain)
        self.bt_10.setObjectName(u"bt_10")
        self.bt_10.setGeometry(QRect(440, 240, 121, 171))
        self.bt_10.setIcon(icon1)
        self.bt_10.setIconSize(QSize(151, 171))
        self.bt_11 = QPushButton(fmain)
        self.bt_11.setObjectName(u"bt_11")
        self.bt_11.setGeometry(QRect(580, 240, 121, 171))
        self.bt_11.setIcon(icon1)
        self.bt_11.setIconSize(QSize(151, 171))
        self.bt_12 = QPushButton(fmain)
        self.bt_12.setObjectName(u"bt_12")
        self.bt_12.setGeometry(QRect(720, 240, 121, 171))
        self.bt_12.setIcon(icon1)
        self.bt_12.setIconSize(QSize(151, 171))
        self.bt_13 = QPushButton(fmain)
        self.bt_13.setObjectName(u"bt_13")
        self.bt_13.setGeometry(QRect(20, 420, 121, 171))
        self.bt_13.setIcon(icon1)
        self.bt_13.setIconSize(QSize(151, 171))
        self.bt_14 = QPushButton(fmain)
        self.bt_14.setObjectName(u"bt_14")
        self.bt_14.setGeometry(QRect(160, 420, 121, 171))
        self.bt_14.setIcon(icon1)
        self.bt_14.setIconSize(QSize(151, 171))
        self.bt_15 = QPushButton(fmain)
        self.bt_15.setObjectName(u"bt_15")
        self.bt_15.setGeometry(QRect(300, 420, 121, 171))
        self.bt_15.setIcon(icon1)
        self.bt_15.setIconSize(QSize(151, 171))
        self.bt_16 = QPushButton(fmain)
        self.bt_16.setObjectName(u"bt_16")
        self.bt_16.setGeometry(QRect(450, 420, 121, 171))
        self.bt_16.setIcon(icon1)
        self.bt_16.setIconSize(QSize(151, 171))
        self.bt_17 = QPushButton(fmain)
        self.bt_17.setObjectName(u"bt_17")
        self.bt_17.setGeometry(QRect(580, 420, 121, 171))
        self.bt_17.setIcon(icon1)
        self.bt_17.setIconSize(QSize(151, 171))
        self.bt_18 = QPushButton(fmain)
        self.bt_18.setObjectName(u"bt_18")
        self.bt_18.setGeometry(QRect(720, 420, 121, 171))
        self.bt_18.setIcon(icon1)
        self.bt_18.setIconSize(QSize(151, 171))

        self.retranslateUi(fmain)

        QMetaObject.connectSlotsByName(fmain)
    # setupUi

    def retranslateUi(self, fmain):
        fmain.setWindowTitle(QCoreApplication.translate("fmain", u"Jogo da mem\u00f3ria Fair Trade", None))
#if QT_CONFIG(tooltip)
        self.btReset.setToolTip(QCoreApplication.translate("fmain", u"Reiniciar jogo", None))
#endif // QT_CONFIG(tooltip)
        self.btReset.setText("")
        self.bt_1.setText("")
        self.bt_2.setText("")
        self.bt_3.setText("")
        self.bt_4.setText("")
        self.bt_5.setText("")
        self.bt_6.setText("")
        self.bt_7.setText("")
        self.bt_8.setText("")
        self.bt_9.setText("")
        self.bt_10.setText("")
        self.bt_11.setText("")
        self.bt_12.setText("")
        self.bt_13.setText("")
        self.bt_14.setText("")
        self.bt_15.setText("")
        self.bt_16.setText("")
        self.bt_17.setText("")
        self.bt_18.setText("")
    # retranslateUi

